import React, { useEffect, useRef, useState } from "react";
import { useTheme } from "@/contexts/theme-context";


interface InteractiveNavigationProps {
  toc: any;
  diagram: any;
}


const InteractiveNavigation: React.FC<InteractiveNavigationProps> = ({ toc, diagram }) => {
  const [mermaidError, setMermaidError] = useState<string | null>(null);
  const [mermaidSVG, setMermaidSVG] = useState<string | null>(null);
  const [isClient, setIsClient] = useState(false);
  const isMermaid = typeof diagram === "string" && diagram.startsWith("graph");
  const hasTOC = Array.isArray(toc) && toc.length > 0;
  const { theme } = useTheme ? useTheme() : { theme: "light" };

  useEffect(() => {
    setIsClient(true);
  }, []);

  useEffect(() => {
    setMermaidError(null);
    setMermaidSVG(null);
    if (!isClient) return;
    // Debug: log the diagram string always
    // eslint-disable-next-line no-console
    console.log("[InteractiveNavigation] Mermaid diagram string received:", diagram);
    if (isMermaid && typeof window !== "undefined") {
      import("mermaid").then((mermaid) => {
        try {
          const mermaidTheme = theme === "dark" ? "dark" : "neutral";
          mermaid.default.initialize({ startOnLoad: false, theme: mermaidTheme });
          Promise.resolve(mermaid.default.render("mermaid-diagram", diagram)).then((result: any) => {
            setMermaidSVG(result.svg);
            // eslint-disable-next-line no-console
            console.log("[Mermaid SVG generated]", result.svg);
          }).catch((err: any) => {
            setMermaidError("[Mermaid render error] " + String(err));
            // eslint-disable-next-line no-console
            console.error("[Mermaid render error]", err);
            // eslint-disable-next-line no-console
            console.error("[Diagram string]", diagram);
          });
        } catch (e) {
          setMermaidError("[Mermaid render exception] " + String(e));
          // eslint-disable-next-line no-console
          console.error("[Mermaid render exception]", e);
          // eslint-disable-next-line no-console
          console.error("[Diagram string]", diagram);
        }
      });
    } else if (!isMermaid) {
      // eslint-disable-next-line no-console
      console.warn("[No valid Mermaid diagram string provided]", diagram);
    }
  }, [diagram, isMermaid, theme, isClient]);

  if (!isClient) return null;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex flex-col gap-8 p-8">
      {hasTOC || isMermaid ? (
        <>
          {isMermaid && (
            <section>
              <h2 className="text-2xl font-bold mb-4 text-gray-900 dark:text-white">Paper Structure Diagram</h2>
              {mermaidError && (
                <div className="bg-red-100 text-red-800 rounded p-3 mt-2 border border-red-300">
                  <b>Mermaid Render Error:</b>
                  <pre className="whitespace-pre-wrap text-xs">{mermaidError}</pre>
                </div>
              )}
              {mermaidSVG ? (
                <div
                  id="mermaid-diagram-container"
                  className="bg-white dark:bg-gray-800 rounded-xl p-6 border-2 border-blue-400 dark:border-blue-500 min-h-[120px] shadow-md mb-2 max-w-3xl mx-auto w-full"
                  style={{
                    minHeight: 180,
                    background: theme === "dark" ? "#18181b" : "#fff",
                    overflowX: "auto",
                    maxWidth: "100%",
                  }}
                >
                  <div
                    className="overflow-x-auto"
                    style={{ width: "100%" }}
                    dangerouslySetInnerHTML={{ __html: mermaidSVG }}
                  />
                </div>
              ) : (
                <div className="bg-yellow-100 text-yellow-800 rounded p-3 mt-2 border border-yellow-300">
                  <b>No SVG generated by Mermaid.</b> Check the browser console for errors and the diagram string below.
                </div>
              )}
            </section>
          )}
          {hasTOC && (
            <section>
              <h2 className="text-2xl font-bold mb-4 text-gray-900 dark:text-white">Interactive Table of Contents</h2>
              <ul className="bg-white dark:bg-gray-800 rounded-xl p-6 text-base border border-gray-200 dark:border-gray-700 shadow-md">
                {toc.map((item: any) => (
                  <li key={item.id || item.title} className="mb-6">
                    <div className="font-semibold mb-2 text-lg text-blue-700 dark:text-blue-300">{item.title}</div>
                    {item.content && (
                      <div className="bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-700 rounded-xl p-4 mb-3 text-base text-gray-900 dark:text-gray-100 whitespace-pre-wrap max-h-60 overflow-y-auto" style={{ fontSize: '1.15rem' }}>
                        {item.content}
                      </div>
                    )}
                    {item.children && item.children.length > 0 && (
                      <ul className="ml-6 list-disc">
                        {item.children.map((child: any) => (
                          <li key={child.id || child.title} className="mb-3">
                            <div className="font-semibold text-blue-600 dark:text-blue-200">{child.title}</div>
                            {child.content && (
                              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-700 rounded-xl p-3 text-base text-gray-900 dark:text-gray-100 whitespace-pre-wrap max-h-48 overflow-y-auto" style={{ fontSize: '1.08rem' }}>
                                {child.content}
                              </div>
                            )}
                          </li>
                        ))}
                      </ul>
                    )}
                  </li>
                ))}
              </ul>
            </section>
          )}
        </>
      ) : (
        <div className="max-w-2xl mx-auto text-center mt-16">
          <h2 className="text-3xl font-bold mb-4 text-gray-900 dark:text-white">Interactive Navigation</h2>
          <p className="text-lg text-gray-700 dark:text-gray-300 mb-6">
            Modern web frameworks (like <b>React/Next.js</b>) support interactive diagrams (using libraries like <b>Mermaid</b>, <b>D3.js</b>, or <b>vis.js</b>) and dynamic, clickable TOCs. Implementation is straightforward with existing tools.
          </p>
          <p className="text-md text-gray-600 dark:text-gray-400 mb-4">
            <b>Why interactive navigation?</b> It enhances user experience, helps users quickly understand paper structure and contributions, and is especially valuable for technical or academic audiences.
          </p>
          <div className="bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-700 rounded-xl p-6 text-blue-800 dark:text-blue-200">
            <b>No interactive content available for this paper.</b><br />
            Please ensure the backend provides section and contribution data, or try another paper.
          </div>
        </div>
      )}
    </div>
  );
};

export default InteractiveNavigation;
